const LANG=document.body.dataset.lang||'pl';
const A='assets/';
const I18N={
pl:{heroTitle:'WYDARZENIA H0C',heroText:'Kalendarz wydarzeń sojuszu i gry. Planuj, bądź aktywny i wspieraj swoje królestwo.',calendar:'KALENDARZ WYDARZEŃ',daily:'KALENDARZ DZIENNY',today:'DZIŚ',menu:'MENU',game:'Wydarzenia gry',hoc:'Wydarzenia H0C',alliance:'Wydarzenia sojuszu',other:'Inne',upcoming:'NAJBLIŻSZE WYDARZENIA',full:'ZOBACZ PEŁNY KALENDARZ',how:'JAK TO DZIAŁA?',range:'31 SIERPNIA – 5 WRZEŚNIA 2026',days:['PON 31.08','WT 01.09','ŚR 02.09','CZW 03.09','PT 04.09','SOB 05.09'],miniDays:['PON','WT','ŚR','CZW','PT','SOB','NIEDZ.'],miniDates:['31','01','02','03','04','05','06'],allDay:'CAŁY DZIEŃ',home:'O H0C',rules:'REGULAMIN',ranks:'RANGI',events:'WYDARZENIA',principles:'ZASADY',team:'JEDNA DRUŻYNA',materials:'MATERIAŁY',updated:'AKTUALIZOWANY KALENDARZ',upText:'Wydarzenia można łatwo dodawać, usuwać lub edytować. Zmiany są widoczne we wszystkich językach.',four:'4 JĘZYKI',fourText:'Pełne tłumaczenie na polski, angielski, niemiecki i rosyjski.',responsive:'RESPONSYWNY',responsiveText:'Kalendarz działa perfekcyjnie na komputerach, tabletach i urządzeniach mobilnych.',design:'PRZEJRZYSTY DESIGN',designText:'Styl H0C – elegancki, czytelny i dopasowany do klimatu Gry o Tron.',howText:'Kalendarz pokazuje wyłącznie wydarzenia widoczne na dostarczonych zrzutach. Nie dodano żadnych wydarzeń ani dat spoza materiałów.',prev:'Poprzedni tydzień',next:'Następny tydzień'},
en:{heroTitle:'HOC EVENTS',heroText:'Alliance and game events calendar. Plan ahead, stay active and support your kingdom.',calendar:'EVENTS CALENDAR',daily:'DAILY CALENDAR',today:'TODAY',menu:'MENU',game:'Game events',hoc:'H0C events',alliance:'Alliance events',other:'Other',upcoming:'UPCOMING EVENTS',full:'VIEW FULL CALENDAR',how:'HOW IT WORKS?',range:'31 AUGUST – 5 SEPTEMBER 2026',days:['MON 31.08','TUE 01.09','WED 02.09','THU 03.09','FRI 04.09','SAT 05.09'],miniDays:['MON','TUE','WED','THU','FRI','SAT','SUN'],miniDates:['31','01','02','03','04','05','06'],allDay:'ALL DAY',home:'ABOUT H0C',rules:'RULES',ranks:'RANKS',events:'EVENTS',principles:'PRINCIPLES',team:'ONE TEAM',materials:'MATERIALS',updated:'UPDATED CALENDAR',upText:'Events can be added, removed or edited easily. Changes are visible in all languages.',four:'4 LANGUAGES',fourText:'Full translation into Polish, English, German and Russian.',responsive:'RESPONSIVE',responsiveText:'Works perfectly on computers, tablets and mobile devices.',design:'CLEAR DESIGN',designText:'H0C style – elegant, readable and matched to the atmosphere of Game of Thrones.',howText:'The calendar shows only events visible in the supplied screenshots. No events or dates beyond the source material have been added.',prev:'Previous week',next:'Next week'},
de:{heroTitle:'HOC EREIGNISSE',heroText:'Kalender der Bündnis- und Spielereignisse. Plane voraus, bleib aktiv und unterstütze dein Königreich.',calendar:'EREIGNISKALENDER',daily:'TAGESKALENDER',today:'HEUTE',menu:'MENÜ',game:'Spielereignisse',hoc:'H0C-Ereignisse',alliance:'Bündnisereignisse',other:'Andere',upcoming:'BEVORSTEHENDE EREIGNISSE',full:'VOLLSTÄNDIGEN KALENDER ANZEIGEN',how:'WIE FUNKTIONIERT ES?',range:'31. AUGUST – 5. SEPTEMBER 2026',days:['MO 31.08','DI 01.09','MI 02.09','DO 03.09','FR 04.09','SA 05.09'],miniDays:['MO','DI','MI','DO','FR','SA','SO'],miniDates:['31','01','02','03','04','05','06'],allDay:'GANZTÄGIG',home:'ÜBER H0C',rules:'REGELN',ranks:'RÄNGE',events:'EREIGNISSE',principles:'PRINZIPIEN',team:'EIN TEAM',materials:'MATERIALIEN',updated:'AKTUALISIERTER KALENDER',upText:'Ereignisse können einfach hinzugefügt, entfernt oder bearbeitet werden. Änderungen sind in allen Sprachen sichtbar.',four:'4 SPRACHEN',fourText:'Vollständige Übersetzung ins Polnische, Englische, Deutsche und Russische.',responsive:'RESPONSIVE',responsiveText:'Funktioniert perfekt auf Computern, Tablets und mobilen Geräten.',design:'KLARES DESIGN',designText:'H0C-Stil – elegant, lesbar und passend zur Atmosphäre von Game of Thrones.',howText:'Der Kalender zeigt ausschließlich Ereignisse, die in den bereitgestellten Screenshots sichtbar sind. Es wurden keine zusätzlichen Ereignisse oder Daten ergänzt.',prev:'Vorherige Woche',next:'Nächste Woche'},
ru:{heroTitle:'СОБЫТИЯ H0C',heroText:'Календарь событий альянса и игры. Планируй заранее, будь активен и поддерживай своё королевство.',calendar:'КАЛЕНДАРЬ СОБЫТИЙ',daily:'ЕЖЕДНЕВНЫЙ КАЛЕНДАРЬ',today:'СЕГОДНЯ',menu:'МЕНЮ',game:'События игры',hoc:'События H0C',alliance:'События альянса',other:'Другие',upcoming:'БЛИЖАЙШИЕ СОБЫТИЯ',full:'ПОКАЗАТЬ ПОЛНЫЙ КАЛЕНДАРЬ',how:'КАК ЭТО РАБОТАЕТ?',range:'31 АВГУСТА – 5 СЕНТЯБРЯ 2026',days:['ПН 31.08','ВТ 01.09','СР 02.09','ЧТ 03.09','ПТ 04.09','СБ 05.09'],miniDays:['ПН','ВТ','СР','ЧТ','ПТ','СБ','ВС'],miniDates:['31','01','02','03','04','05','06'],allDay:'ВЕСЬ ДЕНЬ',home:'О H0C',rules:'ПРАВИЛА',ranks:'РАНГИ',events:'СОБЫТИЯ',principles:'ПРИНЦИПЫ',team:'ОДНА КОМАНДА',materials:'МАТЕРИАЛЫ',updated:'АКТУАЛЬНЫЙ КАЛЕНДАРЬ',upText:'События можно легко добавлять, удалять или редактировать. Изменения видны на всех языках.',four:'4 ЯЗЫКА',fourText:'Полный перевод на польский, английский, немецкий и русский языки.',responsive:'АДАПТИВНЫЙ',responsiveText:'Календарь отлично работает на компьютерах, планшетах и мобильных устройствах.',design:'ПРОЗРАЧНЫЙ ДИЗАЙН',designText:'Стиль H0C – элегантный, понятный и соответствующий атмосфере Игры престолов.',howText:'Календарь показывает только события, видимые на предоставленных скриншотах. Дополнительные события и даты не добавлялись.',prev:'Предыдущая неделя',next:'Следующая неделя'}};
const T=I18N[LANG]||I18N.pl;
const EVENTS=[
{id:'amber',start:0,end:5,kind:'game amber',icon:'event-amber.png',pl:'Święto Bursztynowej Jesieni',en:'Amber Autumn Feast',de:'Bernstein-Herbstfest',ru:'Праздник янтарной осени',time:null},
{id:'return',start:0,end:5,kind:'game return',icon:'event-return.png',pl:'Powrót do Westeros',en:'Return to Westeros',de:'Rückkehr nach Westeros',ru:'Возвращение в Вестерос',time:null},
{id:'army',start:0,end:0,kind:'game army',icon:'event-army.png',pl:'Zbieranie armii',en:'Army Gathering',de:'Armee sammeln',ru:'Сбор армии',time:null},
{id:'trade',start:0,end:4,kind:'hoc trade',icon:'event-trade.svg',pl:'Dzień Handlowy',en:'Trade Day',de:'Handelstag',ru:'Торговый день',time:'10:00'},
{id:'mobil',start:0,end:4,kind:'alliance mobil',icon:'event-mobil.svg',pl:'Mobilizacja Przymierza',en:'Alliance Mobilization',de:'Allianzmobilisierung',ru:'Мобилизация альянса',time:'20:00'},
{id:'fireworks',start:2,end:3,kind:'game fireworks',icon:'event-fireworks.png',pl:'Spadające Fajerwerki',en:'Falling Fireworks',de:'Fallende Feuerwerke',ru:'Падающие фейерверки',time:'18:00'},
{id:'trial',start:2,end:4,kind:'game winter',icon:'event-winter.png',pl:'Próba Winterfell',en:'Winterfell Trial',de:'Winterfell-Prüfung',ru:'Испытание Винтерфелла',time:'20:00'},
{id:'battle',start:2,end:3,kind:'game battle',icon:'event-battle.png',pl:'Pole bitwy',en:'Battlefield',de:'Schlachtfeld',ru:'Поле битвы',time:null},
{id:'navigator',start:2,end:4,kind:'game navigator',icon:'event-navigator-clean.png',pl:'Nawigator',en:'Navigator',de:'Navigator',ru:'Навигатор',time:null},
{id:'smoke',start:3,end:5,kind:'game smoke',icon:'event-smoke-clean.png',pl:'Zagubieni w dymie',en:'Lost in the Smoke',de:'Im Rauch verloren',ru:'Затерянные в дыму',time:'18:00'},
{id:'night',start:3,end:5,kind:'game night',icon:'event-night.png',pl:'Najazd Króla Nocy',en:'Night King Invasion',de:'Invasion des Nachtkönigs',ru:'Вторжение Короля Ночи',time:'20:00'},
{id:'advisor',start:2,end:5,kind:'game advisor',icon:'event-advisor.png',pl:'Ograniczony czas – Pula Kart Doradcy',en:'Limited Time Advisor Card Pool',de:'Zeitlich begrenzter Beraterkarten-Pool',ru:'Ограниченный набор карт советников',time:null}
];
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const icon=e=>`<span class="event-icon"><img src="${A}${e.icon}" alt="" aria-hidden="true"></span>`;
function setText(){document.querySelectorAll('[data-i18n]').forEach(el=>{const v=T[el.dataset.i18n];if(v!=null)el.textContent=v});document.querySelectorAll('[data-i18n-aria]').forEach(el=>{const v=T[el.dataset.i18nAria];if(v!=null)el.setAttribute('aria-label',v)});document.getElementById('range').textContent=T.range;document.title=`${T.events} H0C | H0C`;}
function renderDays(){document.getElementById('days').innerHTML=T.days.map((d,i)=>`<button class="day ${i===0?'selected':''}" type="button" data-day="${i}">${d}</button>`).join('');document.getElementById('mini-week').innerHTML=T.miniDays.map((d,i)=>`<button class="mini-day ${i===0?'selected':''}" type="button" data-day="${i}"><b>${d}</b><strong>${T.miniDates[i]}</strong></button>`).join('');document.querySelectorAll('.day,.mini-day').forEach(b=>b.addEventListener('click',()=>selectDay(Number(b.dataset.day))));}
function selectDay(i){document.querySelectorAll('.day').forEach(b=>b.classList.toggle('selected',Number(b.dataset.day)===i));document.querySelectorAll('.mini-day').forEach(b=>b.classList.toggle('selected',Number(b.dataset.day)===i));}
function renderTimeline(){const tl=document.getElementById('timeline');tl.innerHTML='';EVENTS.forEach((e,row)=>{const left=e.start/6*100,width=(e.end-e.start+1)/6*100;const r=document.createElement('div');r.className='event-row';r.style.top=`${row*49}px`;r.innerHTML=`<div class="event-bar ${e.kind}" style="left:${left}%;width:calc(${width}% - 10px)">${icon(e)}<span class="event-label">${esc(e[LANG])}</span><span class="event-time">${e.time||T.allDay}</span></div>`;tl.appendChild(r)});tl.style.height=`${EVENTS.length*49+8}px`;}
function renderDaily(){document.getElementById('daily-list').innerHTML=EVENTS.map(e=>`<div class="daily-item ${e.kind}">${icon(e)}<span class="daily-copy"><strong>${esc(e[LANG])}</strong><small>${e.time||T.allDay}</small></span></div>`).join('');}
function renderUpcoming(){const ids=['amber','fireworks','trial','night'];document.getElementById('upcoming-grid').innerHTML=ids.map(id=>EVENTS.find(e=>e.id===id)).map(e=>`<article class="up-item">${icon(e)}<div><h3>${esc(e[LANG])}</h3><p>${T.miniDates[e.start]} – ${T.miniDates[e.end]} · ${e.time||T.allDay}</p></div></article>`).join('');}
document.addEventListener('DOMContentLoaded',()=>{setText();renderDays();renderTimeline();renderDaily();renderUpcoming();const today=document.getElementById('today-btn');today.addEventListener('click',()=>selectDay(0));document.getElementById('prev-week').addEventListener('click',()=>selectDay(0));document.getElementById('next-week').addEventListener('click',()=>selectDay(5));const toggle=document.getElementById('menu-toggle'),nav=document.getElementById('site-nav');toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));});});
