const DATA={
pl:{code:'pl',home:'O H0C',rules:'REGULAMIN',ranks:'RANGI',events:'WYDARZENIA',principles:'ZASADY',team:'JEDNA DRUŻYNA',materials:'MATERIAŁY',hero:'WYDARZENIA H0C',heroText:'Kalendarz wydarzeń sojuszu i gry. Planuj, bądź aktywny i wspieraj swoje królestwo.',calendar:'KALENDARZ WYDARZEŃ',daily:'KALENDARZ DZIENNY',today:'DZIŚ',game:'Wydarzenia gry',hoc:'Wydarzenia H0C',alliance:'Wydarzenia sojuszu',other:'Inne',upcoming:'NAJBLIŻSZE WYDARZENIA',full:'ZOBACZ PEŁNY KALENDARZ',range:'31 SIERPNIA – 5 WRZEŚNIA 2026',days:['PON 31.08','WT 01.09','ŚR 02.09','CZW 03.09','PT 04.09','SOB 05.09'],mini:['PON','WT','ŚR','CZW','PT','SOB','NIEDZ.'],dates:['31.08','01.09','02.09','03.09','04.09','05.09','06.09'],allDay:'CAŁY DZIEŃ',how:'JAK TO DZIAŁA?',howText:'Dowiedz się więcej o wydarzeniach i zasadach ich rozgrywania.',info:[['WSPÓŁPRACA','Działajcie razem, komunikujcie się i wspierajcie swoje królestwo.'],['AKTYWNOŚĆ','Bierz udział w wydarzeniach i zdobywaj cenne nagrody.'],['STRATEGIA','Dobre planowanie to klucz do zwycięstwa.'],['CHWAŁA','Walczcie o honor, chwałę i potęgę swojego sojuszu.']]},
en:{code:'en',home:'ABOUT H0C',rules:'RULES',ranks:'RANKS',events:'EVENTS',principles:'PRINCIPLES',team:'ONE TEAM',materials:'MATERIALS',hero:'HOC EVENTS',heroText:'Alliance and game events calendar. Plan ahead, stay active and support your kingdom.',calendar:'EVENTS CALENDAR',daily:'DAILY CALENDAR',today:'TODAY',game:'Game events',hoc:'H0C events',alliance:'Alliance events',other:'Other',upcoming:'UPCOMING EVENTS',full:'VIEW FULL CALENDAR',range:'31 AUGUST – 5 SEPTEMBER 2026',days:['MON 31.08','TUE 01.09','WED 02.09','THU 03.09','FRI 04.09','SAT 05.09'],mini:['MON','TUE','WED','THU','FRI','SAT','SUN'],dates:['31.08','01.09','02.09','03.09','04.09','05.09','06.09'],allDay:'ALL DAY',how:'HOW IT WORKS?',howText:'Learn more about events and how they are played.',info:[['COOPERATION','Work together, communicate and support your kingdom.'],['ACTIVITY','Take part in events and earn valuable rewards.'],['STRATEGY','Good planning is the key to victory.'],['GLORY','Fight for the honor, glory and power of your alliance.']]},
de:{code:'de',home:'ÜBER H0C',rules:'REGELN',ranks:'RÄNGE',events:'EREIGNISSE',principles:'PRINZIPIEN',team:'EIN TEAM',materials:'MATERIALIEN',hero:'HOC EREIGNISSE',heroText:'Kalender der Bündnis- und Spielereignisse. Plane voraus, bleib aktiv und unterstütze dein Königreich.',calendar:'EREIGNISKALENDER',daily:'TAGESKALENDER',today:'HEUTE',game:'Spielereignisse',hoc:'H0C-Ereignisse',alliance:'Bündnisereignisse',other:'Andere',upcoming:'BEVORSTEHENDE EREIGNISSE',full:'VOLLSTÄNDIGEN KALENDER ANZEIGEN',range:'31. AUGUST – 5. SEPTEMBER 2026',days:['MO 31.08','DI 01.09','MI 02.09','DO 03.09','FR 04.09','SA 05.09'],mini:['MO','DI','MI','DO','FR','SA','SO'],dates:['31.08','01.09','02.09','03.09','04.09','05.09','06.09'],allDay:'GANZTÄGIG',how:'WIE FUNKTIONIERT ES?',howText:'Erfahre mehr über die Ereignisse und ihre Regeln.',info:[['ZUSAMMENARBEIT','Arbeitet zusammen, kommuniziert und unterstützt euer Königreich.'],['AKTIVITÄT','Nehmt an Ereignissen teil und verdient wertvolle Belohnungen.'],['STRATEGIE','Gute Planung ist der Schlüssel zum Sieg.'],['RUHM','Kämpft für Ehre, Ruhm und die Macht eures Bündnisses.']]},
ru:{code:'ru',home:'О H0C',rules:'ПРАВИЛА',ranks:'РАНГИ',events:'СОБЫТИЯ',principles:'ПРИНЦИПЫ',team:'ОДНА КОМАНДА',materials:'МАТЕРИАЛЫ',hero:'СОБЫТИЯ H0C',heroText:'Календарь событий альянса и игры. Планируй заранее, будь активен и поддерживай своё королевство.',calendar:'КАЛЕНДАРЬ СОБЫТИЙ',daily:'ЕЖЕДНЕВНЫЙ КАЛЕНДАРЬ',today:'СЕГОДНЯ',game:'События игры',hoc:'События H0C',alliance:'События альянса',other:'Другие',upcoming:'БЛИЖАЙШИЕ СОБЫТИЯ',full:'ПОКАЗАТЬ ПОЛНЫЙ КАЛЕНДАРЬ',range:'31 АВГУСТА – 5 СЕНТЯБРЯ 2026',days:['ПН 31.08','ВТ 01.09','СР 02.09','ЧТ 03.09','ПТ 04.09','СБ 05.09'],mini:['ПН','ВТ','СР','ЧТ','ПТ','СБ','ВС'],dates:['31.08','01.09','02.09','03.09','04.09','05.09'],allDay:'ВЕСЬ ДЕНЬ',how:'КАК ЭТО РАБОТАЕТ?',howText:'Узнай больше о событиях и правилах их проведения.',info:[['СОТРУДНИЧЕСТВО','Действуйте вместе, общайтесь и поддерживайте своё королевство.'],['АКТИВНОСТЬ','Участвуйте в событиях и получайте ценные награды.'],['СТРАТЕГИЯ','Хорошее планирование — ключ к победе.'],['СЛАВА','Сражайтесь за честь, славу и силу вашего альянса.']]}}
const E=[
{id:'amber',s:0,e:5,kind:'red',icon:'amber',name:{pl:'Święto Bursztynowej Jesieni',en:'Amber Autumn Feast',de:'Bernstein-Herbstfest',ru:'Праздник янтарной осени'},time:null},
{id:'return',s:0,e:5,kind:'game',icon:'return',name:{pl:'Powrót do Westeros',en:'Return to Westeros',de:'Rückkehr nach Westeros',ru:'Возвращение в Вестерос'},time:null},
{id:'army',s:0,e:0,kind:'army',icon:'army',name:{pl:'Zbieranie armii',en:'Army Gathering',de:'Armee sammeln',ru:'Сбор армии'},time:null},
{id:'trade',s:0,e:4,kind:'trade',icon:'trade',name:{pl:'Dzień handlowy',en:'Trade Day',de:'Handelstag',ru:'Торговый день'},time:'10:00'},
{id:'mobil',s:0,e:4,kind:'mobil',icon:'mobil',name:{pl:'Mobilizacja Przymierza',en:'Alliance Mobilization',de:'Bündnismobilisierung',ru:'Мобилизация альянса'},time:'20:00'},
{id:'fireworks',s:2,e:3,kind:'fire',icon:'fireworks',name:{pl:'Spadające fajerwerki',en:'Falling Fireworks',de:'Fallende Feuerwerke',ru:'Падающие фейерверки'},time:'18:00'},
{id:'winter',s:2,e:4,kind:'winter',icon:'winter',name:{pl:'Próba Winterfell',en:'Winterfell Trial',de:'Winterfell-Prüfung',ru:'Испытание Винтерфелла'},time:'20:00'},
{id:'battle',s:2,e:3,kind:'battle',icon:'battle',name:{pl:'Pole bitwy',en:'Battlefield',de:'Schlachtfeld',ru:'Поле битвы'},time:null},
{id:'navigator',s:2,e:4,kind:'nav',icon:'navigator',name:{pl:'Nawigator',en:'Navigator',de:'Navigator',ru:'Навигатор'},time:null},
{id:'smoke',s:3,e:5,kind:'smoke',icon:'smoke',name:{pl:'Zagubieni w dymie',en:'Lost in the Smoke',de:'Im Rauch verloren',ru:'Затерянные в дыму'},time:'18:00'},
{id:'night',s:3,e:5,kind:'night',icon:'night',name:{pl:'Najazd Króla Nocy',en:'Night King Invasion',de:'Invasion des Nachtkönigs',ru:'Вторжение Короля Ночи'},time:'20:00'},
{id:'advisor',s:2,e:5,kind:'advisor',icon:'advisor',name:{pl:'Ograniczony czas – Pula Kart',en:'Limited Time – Advisor Card Pool',de:'Zeitlich begrenzter Beraterkarten-Pool',ru:'Ограниченный набор карт советников'},time:null}
]
const A='assets/icon-'; const icon=e=>`<img src="${A+e.icon}.png" alt="" class="icon">`; const txt=(e,l)=>e.name[l];
function nav(t,l){const homeFile=l==='pl'?'index.html':l+'.html';return `<a href="${homeFile}" data-home>${t.home}</a><a href="${homeFile}#rules">${t.rules}</a><a href="${homeFile}#ranks">${t.ranks}</a><a href="events${l==='pl'?'': '-'+l}.html" class="active">${t.events}</a><a href="${homeFile}#principles">${t.principles}</a><a href="${homeFile}#team">${t.team}</a><a href="${homeFile}#materials">${t.materials}</a>`}
function flag(code){const f={pl:['#fff','#dc143c'],de:['#000','#dd0000','#ffce00'],ru:['#fff','#0039a6','#d52b1e']} ; if(code==='en')return `<svg class="flag" viewBox="0 0 60 40"><rect width="60" height="40" fill="#012169"/><path d="M0 0L60 40M60 0L0 40" stroke="#fff" stroke-width="9"/><path d="M0 0L60 40M60 0L0 40" stroke="#c8102e" stroke-width="5"/><path d="M30 0V40M0 20H60" stroke="#fff" stroke-width="15"/><path d="M30 0V40M0 20H60" stroke="#c8102e" stroke-width="9"/></svg>`;return `<svg class="flag" viewBox="0 0 60 40">${f[code].map((c,i)=>`<rect y="${i*40/f[code].length}" width="60" height="${40/f[code].length}" fill="${c}"/>`).join('')}</svg>`}
function render(){const l=document.body.dataset.lang||'pl',t=DATA[l];document.documentElement.lang=l;document.querySelector('.brand').href=l==='pl'?'index.html':l+'.html';document.title=`${t.events} H0C | H0C`;document.querySelector('.site-nav').innerHTML=nav(t,l);document.querySelector('.flags').innerHTML=['pl','en','de','ru'].map(c=>`<a href="events${c==='pl'?'':'-'+c}.html" aria-label="${c}">${flag(c)}</a>`).join('');document.querySelector('.hero h1').textContent=t.hero;document.querySelector('.hero p:last-child').textContent=t.heroText;document.querySelectorAll('[data-text]').forEach(x=>x.textContent=t[x.dataset.text]);document.querySelector('#range').textContent=t.range;document.querySelector('.week').innerHTML=t.days.map((d,i)=>`<button class="day ${i===0?'selected':''}" data-day="${i}">${d}</button>`).join('');document.querySelector('.daily-date').innerHTML=`<span class="daily-date-flag">${flag(l)}</span>${t.days[0]}`;document.querySelector('.daily-week').innerHTML=t.mini.map((d,i)=>`<div class="mini-day ${i===0?'selected':''}">${d}<strong>${t.dates[i]}</strong></div>`).join('');
const tl=document.querySelector('.timeline');tl.innerHTML=E.map((e,i)=>{const left=e.s/6*100,width=(e.e-e.s+1)/6*100;return `<div class="event ${e.kind}" style="top:${i*42+8}px;left:${left}%;width:calc(${width}% - 8px)">${icon(e)}<span class="name">${txt(e,l)}</span><span class="time">${e.time||t.allDay}</span></div>`}).join('');tl.style.height=`${E.length*42+16}px`;
document.querySelector('.daily-list').innerHTML=E.map(e=>`<div class="daily-item ${e.kind}">${icon(e)}<strong>${txt(e,l)}</strong><small>${e.time||t.allDay}</small></div>`).join('');const up=['amber','fireworks','winter','night'];document.querySelector('.up-grid').innerHTML=up.map(id=>{const e=E.find(x=>x.id===id);return `<article class="up-item">${icon(e)}<div><h4>${txt(e,l)}</h4><strong>${e.time||t.allDay}</strong><p>${t.dates[e.s]} – ${t.dates[e.e]}</p></div></article>`}).join('');document.querySelector('.info-grid').innerHTML=t.info.map((x,i)=>`<article class="info"><img class="info-img" src="assets/info-${['cooperation','activity','strategy','glory'][i]}.png" alt=""><div><h4>${x[0]}</h4><p>${x[1]}</p></div></article>`).join('');
}
function wire(){document.addEventListener('click',e=>{const b=e.target.closest('.day,.mini-day');if(b){document.querySelectorAll('.day,.mini-day').forEach(x=>x.classList.remove('selected'));const i=Number(b.dataset.day);document.querySelectorAll(`.day[data-day="${i}"],.mini-day:nth-child(${i+1})`).forEach(x=>x.classList.add('selected'))}if(e.target.closest('.today')){document.querySelector('.day').click()}const m=e.target.closest('#menu-toggle');if(m){document.querySelector('.site-nav').classList.toggle('open')}})}
document.addEventListener('DOMContentLoaded',()=>{render();wire()});
